using Default;
using Microsoft.OData.Client;
using ODataService.Models;

// Strongly-typed OData client generated by the OData Connected Service.
// Start ODataService first (it listens on http://localhost:5251).

string serviceRoot = args.Length > 0 ? args[0] : "http://localhost:5251/odata";

var container = new Container(new Uri(serviceRoot))
{
    MergeOption = MergeOption.OverwriteChanges,
};

Console.WriteLine($"OData service root: {container.BaseUri}\n");

// Query 1: all customers
Console.WriteLine("=== All customers ===");
foreach (Customer c in container.Customers)
{
    PrintCustomer(c);
}

// Query 2: LINQ filter + orderby (translated to $filter/$orderby)
Console.WriteLine("\n=== City == 'Redmond', ordered by Name desc ===");
var redmond = container.Customers
    .Where(c => c.City == "Redmond")
    .OrderByDescending(c => c.Name);
foreach (Customer c in redmond)
{
    PrintCustomer(c);
}

// Query 3: expand navigation property (Orders)
Console.WriteLine("\n=== Customers with their Orders ($expand) ===");
var withOrders = container.Customers.Expand(c => c.Orders);
foreach (Customer c in withOrders)
{
    PrintCustomer(c);
    foreach (Order o in c.Orders)
    {
        Console.WriteLine($"    Order #{o.Id}: {o.Product} (${o.Amount})");
    }
}

// Query 4: single entity by key
Console.WriteLine("\n=== Single customer by key (1) ===");
Customer single = container.Customers.ByKey(1).GetValue();
PrintCustomer(single);

static void PrintCustomer(Customer c)
{
    string lastOrder = c.LastOrderDate.HasValue ? c.LastOrderDate.Value.ToString("o") : "(none)";
    Console.WriteLine($"  [{c.Id}] {c.Name}, {c.City}, {c.Category}, registered {c.RegisteredAt:o}, last order {lastOrder}");
}
