@DeepInsertVsDeepUpdate_HostAddress = http://localhost:5064

GET {{DeepInsertVsDeepUpdate_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{DeepInsertVsDeepUpdate_HostAddress}}/odata/AgentInstances?$expand=manifest,manifest2

###
GET {{DeepInsertVsDeepUpdate_HostAddress}}/odata/manifests

###
POST {{DeepInsertVsDeepUpdate_HostAddress}}/odata/AgentInstances
Content-Type: application/json

{
  "Name": "New Agent Instance",
  "Manifest": {
    "Id": 3,
    "DisplayName": "New Manifest"
  },
  "Manifest2": {
    "Id": 31,
    "DisplayName": "New Manifest2"
  }
}

###
POST {{DeepInsertVsDeepUpdate_HostAddress}}/odata/AgentInstances
Content-Type: application/json

{
  "Name": "New Agent Instance to link the existed manifest, meanwhile create a Manifeat2 ",
  "Manifest": {
    "@odata.id": "Manifests(2)"
  },
  "Manifest2": {
     "Id": 41,
     "DisplayName": "New 41 Manifest2"
  }
}


###
# It will fail since '51' is not existed
POST {{DeepInsertVsDeepUpdate_HostAddress}}/odata/AgentInstances
Content-Type: application/json

{
  "Name": "New Agent Instance to link the existed manifest",
  "Manifest": {
    "@odata.id": "Manifests(51)"
  },
  "Manifest2": {
     "Id": 61,
     "DisplayName": "New 61 Manifest2"
  }
}

###
POST {{DeepInsertVsDeepUpdate_HostAddress}}/odata/AgentInstances
Content-Type: application/json

{
  "Name": "New Agent Instance to using OData.bind",
  "Manifest@odata.bind": "Manifests(2)",
  "Manifest2@odata.bind": "Manifests(1)"
}


###

PATCH {{DeepInsertVsDeepUpdate_HostAddress}}/odata/AgentInstances
Accept: application/json
Content-Type: application/json
OData-Version: 4.01

{
  "@odata.context": "http://localhost:5064/odata/$metadata#AgentInstances/$delta",
  "value": [
    {
      "Id": 121,
      "Manifest@delta":
        {
          "Id": 0,
          "DisplayName": "Changed DisplayName"
        }
    },
    {
      "@odata.removed": {
        "reason": "deleted"
      },
      "@odata.id": "http://localhost:5064/odata/AgentInstances(31)"
    }
  ]
}

###

PATCH {{DeepInsertVsDeepUpdate_HostAddress}}/odata/AgentInstances/11
Accept: application/json
Content-Type: application/json
OData-Version: 4.01

{
    "Name": "New Same Name",
    "Manifest@delta":
      {
        "Id": 0,
        "DisplayName": "Changed Update DisplayName"
      }
}
